USE xyz_fidelizacion;
-- ====== INSERTS: PERFILES (10) ======
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (1,'Administrador','2025-01-01','Acceso total al sistema','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (2,'RRHH','2025-01-01','Gestión de personal y beneficios','RRHH');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (3,'Analista','2025-01-01','Análisis de datos y reportes','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (4,'Supervisor','2025-01-01','Supervisión de equipos y aprobaciones','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (5,'Colaborador','2025-01-01','Acceso estándar a funciones básicas','RRHH');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (6,'Finanzas','2025-01-01','Gestión financiera y nómina','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (7,'Soporte TI','2025-01-01','Soporte técnico y mantenimiento','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (8,'Gerencia','2025-01-01','Acceso gerencial y KPIs','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (9,'Auditor','2025-01-01','Revisión y control interno','Gerencia');
INSERT INTO perfiles (perfil_id,nombre_perfil,fecha_vigencia_perfil,descripcion_perfil,encargado_perfil) VALUES (10,'Invitado','2025-01-01','Acceso limitado de consulta','Gerencia');

-- ====== INSERTS: USUARIOS (20) ======
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (1,'Ana','García','activo','$2y$10$demo_hash_01','Analista de Datos',1200.00,'2022-03-10',3);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (2,'Luis','Pérez','activo','$2y$10$demo_hash_02','Supervisor de Operaciones',1500.00,'2021-07-01',4);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (3,'María','Rodríguez','activo','$2y$10$demo_hash_03','Especialista RRHH',1400.00,'2020-11-15',2);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (4,'Carlos','Sánchez','activo','$2y$10$demo_hash_04','Soporte TI',1300.00,'2023-01-20',7);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (5,'Elena','Martínez','activo','$2y$10$demo_hash_05','Asistente Administrativo',950.00,'2024-05-05',5);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (6,'Jorge','Gómez','activo','$2y$10$demo_hash_06','Analista Financiero',1600.00,'2019-09-09',6);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (7,'Sofía','Díaz','activo','$2y$10$demo_hash_07','Auditor Interno',1700.00,'2018-04-02',9);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (8,'Pedro','Torres','activo','$2y$10$demo_hash_08','Colaborador',900.00,'2024-02-12',5);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (9,'Valentina','Castro','activo','$2y$10$demo_hash_09','Gerente de Área',2500.00,'2017-06-30',8);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (10,'Ricardo','Vargas','activo','$2y$10$demo_hash_10','Administrador de Sistemas',2200.00,'2016-08-18',1);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (11,'Isabel','Morales','activo','$2y$10$demo_hash_11','Colaborador',920.00,'2024-07-07',5);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (12,'Daniel','Rojas','activo','$2y$10$demo_hash_12','Analista de Procesos',1350.00,'2022-10-25',3);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (13,'Camila','Herrera','activo','$2y$10$demo_hash_13','Supervisor de Turno',1450.00,'2021-02-14',4);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (14,'Miguel','Navarro','activo','$2y$10$demo_hash_14','Contador',1550.00,'2020-12-01',6);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (15,'Paula','Ortega','activo','$2y$10$demo_hash_15','Especialista RRHH',1420.00,'2023-03-03',2);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (16,'Andrés','Flores','activo','$2y$10$demo_hash_16','Soporte TI',1280.00,'2022-06-16',7);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (17,'Natalia','Ruiz','inactivo','$2y$10$demo_hash_17','Analista de Datos',1250.00,'2021-09-21',3);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (18,'Fernando','Silva','activo','$2y$10$demo_hash_18','Colaborador',880.00,'2024-01-10',5);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (19,'Lucía','Mendoza','activo','$2y$10$demo_hash_19','Auditor',1750.00,'2019-01-28',9);
INSERT INTO usuarios (usuario_id,nombre,apellido,estado,contrasena,cargo,salario,fecha_ingreso,perfil_id) VALUES (20,'Diego','Reyes','activo','$2y$10$demo_hash_20','Invitado',0.00,'2025-09-01',10);

-- ====== INSERTS: ACTIVIDADES (24 = 2 por mes / 12 meses) ======
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (1,'2025-01-05','Team Building','Actividad Team Building - Mes 01',31);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (2,'2025-01-20','Deportes','Actividad Deportes - Mes 01',57);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (3,'2025-02-05','Capacitación','Actividad Capacitación - Mes 02',29);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (4,'2025-02-20','Innovación','Actividad Innovación - Mes 02',56);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (5,'2025-03-05','Voluntariado','Actividad Voluntariado - Mes 03',58);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (6,'2025-03-20','Bienestar','Actividad Bienestar - Mes 03',35);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (7,'2025-04-05','Deportes','Actividad Deportes - Mes 04',57);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (8,'2025-04-20','Team Building','Actividad Team Building - Mes 04',58);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (9,'2025-05-05','Innovación','Actividad Innovación - Mes 05',27);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (10,'2025-05-20','Capacitación','Actividad Capacitación - Mes 05',28);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (11,'2025-06-05','Bienestar','Actividad Bienestar - Mes 06',41);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (12,'2025-06-20','Voluntariado','Actividad Voluntariado - Mes 06',57);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (13,'2025-07-05','Team Building','Actividad Team Building - Mes 07',44);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (14,'2025-07-20','Deportes','Actividad Deportes - Mes 07',46);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (15,'2025-08-05','Capacitación','Actividad Capacitación - Mes 08',55);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (16,'2025-08-20','Innovación','Actividad Innovación - Mes 08',50);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (17,'2025-09-05','Voluntariado','Actividad Voluntariado - Mes 09',28);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (18,'2025-09-20','Bienestar','Actividad Bienestar - Mes 09',37);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (19,'2025-10-05','Deportes','Actividad Deportes - Mes 10',30);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (20,'2025-10-20','Team Building','Actividad Team Building - Mes 10',39);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (21,'2025-11-05','Innovación','Actividad Innovación - Mes 11',43);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (22,'2025-11-20','Capacitación','Actividad Capacitación - Mes 11',45);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (23,'2025-12-05','Bienestar','Actividad Bienestar - Mes 12',48);
INSERT INTO actividades (actividad_id,fecha_actividad,tipo_actividad,descripcion_actividad,puntos_otorgados) VALUES (24,'2025-12-20','Voluntariado','Actividad Voluntariado - Mes 12',34);

-- ====== INSERTS: PARTICIPACIÓN EN ACTIVIDADES (Fidelización) ======
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (1,1,1,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (2,2,1,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (3,3,1,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (4,6,1,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (5,7,1,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (6,8,1,34);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (7,9,1,34);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (8,10,1,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (9,12,1,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (10,15,1,28);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (11,18,1,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (12,19,1,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (13,20,1,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (14,1,2,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (15,2,2,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (16,3,2,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (17,4,2,56);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (18,6,2,57);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (19,7,2,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (20,8,2,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (21,9,2,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (22,12,2,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (23,14,2,57);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (24,15,2,62);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (25,16,2,62);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (26,19,2,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (27,1,3,34);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (28,2,3,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (29,6,3,24);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (30,7,3,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (31,8,3,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (32,10,3,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (33,11,3,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (34,12,3,34);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (35,14,3,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (36,18,3,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (37,19,3,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (38,1,4,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (39,2,4,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (40,4,4,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (41,6,4,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (42,7,4,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (43,9,4,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (44,11,4,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (45,14,4,61);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (46,15,4,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (47,16,4,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (48,17,4,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (49,1,5,63);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (50,2,5,63);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (51,4,5,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (52,6,5,61);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (53,9,5,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (54,13,5,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (55,14,5,62);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (56,16,5,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (57,1,6,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (58,2,6,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (59,4,6,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (60,6,6,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (61,7,6,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (62,9,6,37);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (63,12,6,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (64,13,6,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (65,16,6,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (66,17,6,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (67,20,6,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (68,1,7,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (69,2,7,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (70,6,7,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (71,7,7,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (72,8,7,62);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (73,9,7,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (74,10,7,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (75,13,7,58);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (76,16,7,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (77,17,7,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (78,18,7,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (79,19,7,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (80,1,8,61);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (81,2,8,63);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (82,7,8,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (83,8,8,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (84,9,8,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (85,11,8,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (86,13,8,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (87,14,8,61);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (88,17,8,56);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (89,1,9,22);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (90,2,9,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (91,5,9,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (92,6,9,24);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (93,7,9,23);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (94,9,9,23);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (95,13,9,23);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (96,14,9,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (97,16,9,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (98,19,9,28);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (99,1,10,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (100,2,10,24);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (101,3,10,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (102,6,10,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (103,7,10,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (104,11,10,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (105,12,10,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (106,17,10,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (107,18,10,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (108,19,10,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (109,2,11,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (110,3,11,45);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (111,4,11,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (112,5,11,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (113,7,11,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (114,9,11,37);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (115,10,11,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (116,11,11,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (117,14,11,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (118,16,11,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (119,17,11,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (120,1,12,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (121,2,12,57);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (122,7,12,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (123,9,12,60);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (124,11,12,61);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (125,14,12,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (126,18,12,57);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (127,1,13,42);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (128,2,13,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (129,3,13,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (130,5,13,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (131,6,13,42);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (132,7,13,49);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (133,8,13,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (134,9,13,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (135,11,13,49);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (136,15,13,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (137,16,13,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (138,17,13,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (139,18,13,48);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (140,19,13,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (141,2,14,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (142,3,14,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (143,5,14,49);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (144,6,14,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (145,7,14,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (146,8,14,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (147,10,14,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (148,13,14,45);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (149,15,14,45);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (150,17,14,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (151,1,15,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (152,2,15,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (153,3,15,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (154,4,15,59);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (155,6,15,57);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (156,7,15,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (157,9,15,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (158,10,15,54);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (159,13,15,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (160,15,15,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (161,16,15,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (162,20,15,56);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (163,2,16,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (164,4,16,55);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (165,9,16,48);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (166,10,16,53);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (167,14,16,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (168,1,17,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (169,2,17,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (170,3,17,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (171,6,17,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (172,7,17,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (173,9,17,33);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (174,10,17,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (175,11,17,27);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (176,12,17,28);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (177,13,17,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (178,14,17,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (179,15,17,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (180,17,17,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (181,18,17,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (182,19,17,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (183,1,18,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (184,3,18,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (185,4,18,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (186,6,18,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (187,9,18,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (188,10,18,35);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (189,12,18,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (190,13,18,37);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (191,2,19,35);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (192,3,19,35);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (193,4,19,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (194,5,19,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (195,6,19,28);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (196,7,19,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (197,9,19,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (198,10,19,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (199,13,19,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (200,14,19,26);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (201,19,19,25);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (202,1,20,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (203,2,20,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (204,5,20,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (205,6,20,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (206,9,20,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (207,11,20,34);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (208,15,20,37);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (209,16,20,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (210,19,20,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (211,1,21,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (212,2,21,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (213,5,21,48);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (214,6,21,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (215,7,21,39);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (216,8,21,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (217,9,21,45);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (218,10,21,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (219,11,21,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (220,13,21,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (221,18,21,41);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (222,20,21,45);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (223,1,22,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (224,2,22,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (225,3,22,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (226,5,22,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (227,6,22,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (228,7,22,49);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (229,9,22,40);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (230,10,22,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (231,11,22,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (232,18,22,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (233,19,22,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (234,1,23,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (235,2,23,48);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (236,3,23,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (237,4,23,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (238,5,23,47);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (239,6,23,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (240,7,23,51);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (241,9,23,46);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (242,10,23,50);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (243,11,23,52);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (244,14,23,44);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (245,16,23,48);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (246,17,23,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (247,19,23,43);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (248,1,24,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (249,2,24,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (250,3,24,29);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (251,6,24,31);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (252,8,24,36);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (253,9,24,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (254,10,24,30);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (255,13,24,38);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (256,15,24,32);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (257,16,24,35);
INSERT INTO participacion_actividad (participacion_id,usuario_id,actividad_id,puntos_ganados) VALUES (258,19,24,37);

-- ====== INSERTS: LOGIN (100) ======
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (1,1,'2025-09-28 01:45:57','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (2,1,'2025-09-29 15:10:30','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (3,1,'2025-10-23 14:29:30','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (4,1,'2025-10-26 07:13:45','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (5,1,'2025-11-23 14:43:33','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (6,2,'2025-08-17 02:21:39','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (7,2,'2025-09-11 07:26:55','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (8,2,'2025-09-21 17:20:25','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (9,2,'2025-11-30 19:06:40','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (10,2,'2025-12-07 13:49:05','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (11,3,'2025-08-07 16:06:45','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (12,3,'2025-09-15 06:45:26','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (13,3,'2025-09-26 21:22:00','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (14,3,'2025-10-31 13:57:03','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (15,3,'2025-11-24 15:21:38','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (16,4,'2025-09-08 17:54:15','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (17,4,'2025-09-21 16:54:50','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (18,4,'2025-11-23 20:37:07','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (19,4,'2025-11-30 16:58:53','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (20,4,'2025-12-07 17:20:10','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (21,5,'2025-08-12 21:56:00','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (22,5,'2025-08-15 04:47:38','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (23,5,'2025-09-02 13:15:22','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (24,5,'2025-09-30 01:34:29','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (25,5,'2025-11-24 21:06:22','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (26,6,'2025-09-23 04:45:33','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (27,6,'2025-10-18 11:49:32','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (28,6,'2025-11-06 12:22:09','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (29,6,'2025-11-14 04:29:47','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (30,6,'2025-12-15 04:59:43','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (31,7,'2025-08-03 20:16:10','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (32,7,'2025-08-10 04:48:25','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (33,7,'2025-08-23 13:25:57','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (34,7,'2025-08-25 15:23:58','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (35,7,'2025-11-02 17:24:55','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (36,8,'2025-08-09 03:29:35','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (37,8,'2025-09-04 08:26:52','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (38,8,'2025-09-22 16:00:44','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (39,8,'2025-10-31 16:41:33','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (40,8,'2025-11-21 05:30:20','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (41,9,'2025-08-19 01:13:13','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (42,9,'2025-10-07 21:36:57','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (43,9,'2025-10-19 15:02:24','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (44,9,'2025-10-31 14:24:25','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (45,9,'2025-11-04 19:36:29','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (46,10,'2025-08-08 11:01:15','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (47,10,'2025-09-26 07:11:32','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (48,10,'2025-10-18 02:14:33','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (49,10,'2025-11-16 03:38:09','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (50,10,'2025-12-07 23:51:47','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (51,11,'2025-08-01 13:21:51','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (52,11,'2025-10-30 00:57:56','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (53,11,'2025-11-09 06:11:32','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (54,11,'2025-11-14 16:40:09','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (55,11,'2025-12-07 00:55:10','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (56,12,'2025-08-11 08:31:41','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (57,12,'2025-08-26 18:33:57','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (58,12,'2025-09-09 20:39:00','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (59,12,'2025-09-22 04:34:20','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (60,12,'2025-11-15 23:32:56','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (61,13,'2025-09-01 02:05:44','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (62,13,'2025-09-16 19:12:25','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (63,13,'2025-09-30 16:12:02','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (64,13,'2025-11-16 07:05:45','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (65,13,'2025-11-27 13:32:51','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (66,14,'2025-08-24 03:25:54','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (67,14,'2025-08-31 05:33:26','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (68,14,'2025-09-27 00:10:24','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (69,14,'2025-11-06 02:35:53','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (70,14,'2025-12-05 02:32:45','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (71,15,'2025-08-29 10:04:49','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (72,15,'2025-09-07 08:18:31','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (73,15,'2025-10-14 19:38:25','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (74,15,'2025-11-16 09:04:53','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (75,15,'2025-11-25 17:18:07','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (76,16,'2025-08-01 19:57:17','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (77,16,'2025-09-22 05:06:53','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (78,16,'2025-10-06 07:56:00','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (79,16,'2025-10-20 21:46:18','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (80,16,'2025-11-07 22:13:44','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (81,17,'2025-08-15 18:15:08','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (82,17,'2025-09-03 20:11:49','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (83,17,'2025-09-13 16:31:51','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (84,17,'2025-09-17 08:35:50','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (85,17,'2025-09-22 14:59:01','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (86,18,'2025-09-15 16:28:47','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (87,18,'2025-09-16 16:54:52','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (88,18,'2025-10-14 16:46:24','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (89,18,'2025-11-20 08:46:12','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (90,18,'2025-12-14 18:34:41','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (91,19,'2025-08-30 20:51:43','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (92,19,'2025-10-14 08:39:57','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (93,19,'2025-10-15 07:15:26','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (94,19,'2025-12-05 22:37:43','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (95,19,'2025-12-08 05:00:50','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (96,20,'2025-08-11 00:20:42','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (97,20,'2025-09-13 01:59:16','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (98,20,'2025-09-21 09:33:17','exitoso');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (99,20,'2025-10-22 09:05:04','fallido');
INSERT INTO login (login_id,usuario_id,fecha_hora_login,estado_login) VALUES (100,20,'2025-10-25 05:00:40','fallido');
